#!/bin/bash
#SBATCH --job-name=build_vllm
#SBATCH --partition=genoa
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=48
#SBATCH --time=01:00:00


# Refer to here for the latest vLLM images: https://hub.docker.com/r/vllm/vllm-openai/tags
VLLM_IMAGE="vllm/vllm-openai:latest"
OUTPUT_PATH=/scratch-shared/$USER/
VLLM_IMAGE_NAME="vllm.sif"

# For storing persistent containers
APPTAINER_CACHEDIR=/dev/shm/$USER/
# For storing during build time
APPTAINER_TMPDIR=/dev/shm/$USER/
mkdir -p $APPTAINER_CACHEDIR $APPTAINER_TMPDIR

# Create definition recipe file
cat > vllm.def <<EOF
Bootstrap: docker
From: $VLLM_IMAGE
	
%environment
    export CUDA_HOME=/usr/local/cuda
    export LD_LIBRARY_PATH=/usr/local/cuda/lib64    
    export PYTHONNOUSERSITE=1
    export LD_PRELOAD=
EOF

# Build the container
echo "Building latest vLLM Apptainer container..."
apptainer build $OUTPUT_PATH/$VLLM_IMAGE_NAME vllm.def
# Clean up temporary apptainer recipe file
rm vllm.def
